export const LANDING = '/';
export const SIGN_UP = '/signup';
export const SIGN_IN = '/signin';
export const HOME = '/home';
export const ACCOUNT = '/account';
export const ADMIN = '/admin';
export const PASSWORD_FORGET = '/pw-forget';
export const CHAT_BOX = '/chat-box';
export const AUTHENTICATION_DOC ='/tutorials/authentication';
export const REALTIMEDB_DOC ='/tutorials/realtimeDB'
export const HOSTING_DOC ='/tutorials/hosting'